import type { ReliefLocation, Team, Headquarters } from './types';

export const HEADQUARTERS: Headquarters = {
  name: 'Nhà Văn hóa Sinh viên – Thủ Đức',
  coordinates: { lat: 10.87, lng: 106.805 }, // approx trung tâm Nhà Văn hóa Sinh viên, Thủ Đức
  address: 'Khu đô thị Đại học Quốc gia TP. HCM, Thành phố Thủ Đức, TP. Hồ Chí Minh, Việt Nam',
};

// Mock data từ các tỉnh miền Trung hay bị bão lũ
export const reliefLocationsData: ReliefLocation[] = [
  {
    id: 'RL-001',
    coordinates: { lat: 15.5694, lng: 108.0194 },
    locationName: 'Xã Trà Leng',
    address: 'Huyện Nam Trà My, Quảng Nam',
    province: 'Quảng Nam',
    urgency: 'high',
    peopleCount: 120,
    needs: { food: true, water: true, medicine: true, emergencyRescue: true },
    status: 'unassigned',
    lastUpdated: '5 phút trước',
    reportedAt: '2024-01-13 14:50',
    description:
      'KHẨN CẤP: Sạt lở đất nghiêm trọng, nhiều hộ dân bị vùi lấp, cần cứu hộ ngay lập tức. Đường sá bị chia cắt hoàn toàn.',
    contactPerson: 'Trưởng thôn Nguyễn Văn Sơn',
    contactPhone: '0905123456',
    dangerScore: 95,
    priorityScore: 98,
  },
  {
    id: 'RL-002',
    coordinates: { lat: 15.8801, lng: 108.338 },
    locationName: 'Thị trấn Hội An',
    address: 'Phố cổ Hội An, Quảng Nam',
    province: 'Quảng Nam',
    urgency: 'high',
    peopleCount: 250,
    needs: { food: true, water: true, medicine: false, emergencyRescue: false },
    status: 'unassigned',
    lastUpdated: '15 phút trước',
    reportedAt: '2024-01-13 14:40',
    description:
      'Ngập lụt nặng do mưa lớn kéo dài, nước dâng cao 1.5m. Nhiều gia đình bị cô lập, cần lương thực và nước sạch khẩn cấp.',
    contactPerson: 'Chủ tịch phường Minh An',
    contactPhone: '0912345678',
    dangerScore: 85,
    priorityScore: 90,
  },
  {
    id: 'RL-003',
    coordinates: { lat: 16.4637, lng: 107.5909 },
    locationName: 'Huyện Hướng Hóa',
    address: 'Huyện Hướng Hóa, Quảng Trị',
    province: 'Quảng Trị',
    urgency: 'high',
    peopleCount: 180,
    needs: { food: true, water: true, medicine: true, emergencyRescue: true },
    status: 'unassigned',
    lastUpdated: '10 phút trước',
    reportedAt: '2024-01-13 14:45',
    description:
      'Lũ quét ập đến bất ngờ, cuốn trôi nhiều nhà cửa. Có người bị thương và mất tích. Cần hỗ trợ y tế và tìm kiếm cứu nạn.',
    contactPerson: 'Ông Trần Văn Minh',
    contactPhone: '0987654321',
    dangerScore: 92,
    priorityScore: 95,
  },
  {
    id: 'RL-004',
    coordinates: { lat: 17.4739, lng: 106.6234 },
    locationName: 'Huyện Hương Khê',
    address: 'Huyện Hương Khê, Hà Tĩnh',
    province: 'Hà Tĩnh',
    urgency: 'medium',
    peopleCount: 95,
    needs: { food: true, water: false, medicine: true, emergencyRescue: false },
    status: 'unassigned',
    lastUpdated: '30 phút trước',
    reportedAt: '2024-01-13 14:25',
    description:
      'Ngập úng cục bộ, cần hỗ trợ lương thực và thuốc men cho người già, trẻ em. Tình hình đang được kiểm soát.',
    contactPerson: 'Bà Lê Thị Hoa',
    contactPhone: '0933444555',
    dangerScore: 65,
    priorityScore: 70,
  },
  {
    id: 'RL-005',
    coordinates: { lat: 16.8201, lng: 107.1004 },
    locationName: 'Thành phố Đông Hà',
    address: 'Đông Hà, Quảng Trị',
    province: 'Quảng Trị',
    urgency: 'medium',
    peopleCount: 150,
    needs: { food: true, water: true, medicine: false, emergencyRescue: false },
    status: 'on-the-way',
    lastUpdated: '20 phút trước',
    reportedAt: '2024-01-13 13:00',
    description: 'Ngập lụt do triều cường kết hợp mưa lớn. Đội cứu trợ đang trên đường đến.',
    contactPerson: 'UBND phường Đông Lễ',
    contactPhone: '0944555666',
    assignedTeamId: 'TEAM-001',
    dangerScore: 60,
    priorityScore: 65,
  },
  {
    id: 'RL-006',
    coordinates: { lat: 15.5753, lng: 107.7852 },
    locationName: 'Huyện Phước Sơn',
    address: 'Huyện Phước Sơn, Quảng Nam',
    province: 'Quảng Nam',
    urgency: 'high',
    peopleCount: 200,
    needs: { food: true, water: true, medicine: true, emergencyRescue: true },
    status: 'assigned',
    lastUpdated: '25 phút trước',
    reportedAt: '2024-01-13 13:30',
    description:
      'Sạt lở núi chặn đường, chia cắt hoàn toàn. Nhiều người bị thương, thiếu lương thực và nước uống.',
    contactPerson: 'Trưởng phòng QLTT',
    contactPhone: '0977888999',
    assignedTeamId: 'TEAM-002',
    dangerScore: 88,
    priorityScore: 92,
  },
  {
    id: 'RL-007',
    coordinates: { lat: 18.3464, lng: 105.9045 },
    locationName: 'Huyện Quỳnh Lưu',
    address: 'Huyện Quỳnh Lưu, Nghệ An',
    province: 'Nghệ An',
    urgency: 'low',
    peopleCount: 50,
    needs: { food: false, water: true, medicine: false, emergencyRescue: false },
    status: 'completed',
    lastUpdated: '2 giờ trước',
    reportedAt: '2024-01-13 11:00',
    description: 'Đã hoàn thành cung cấp nước sạch. Tình hình ổn định.',
    contactPerson: 'Trưởng xã Quỳnh Thắng',
    contactPhone: '0901234567',
    dangerScore: 30,
    priorityScore: 25,
  },
  {
    id: 'RL-008',
    coordinates: { lat: 16.0678, lng: 108.2208 },
    locationName: 'Quận Sơn Trà',
    address: 'Quận Sơn Trà, Đà Nẵng',
    province: 'Đà Nẵng',
    urgency: 'medium',
    peopleCount: 80,
    needs: { food: false, water: false, medicine: true, emergencyRescue: false },
    status: 'unassigned',
    lastUpdated: '40 phút trước',
    reportedAt: '2024-01-13 14:15',
    description: 'Cần hỗ trợ thuốc men cho bệnh nhân mãn tính do gián đoạn chuỗi cung ứng.',
    contactPerson: 'Trạm y tế phường Thọ Quang',
    contactPhone: '0905111222',
    dangerScore: 45,
    priorityScore: 55,
  },
  {
    id: 'RL-009',
    coordinates: { lat: 17.5883, lng: 106.3503 },
    locationName: 'Huyện Kỳ Anh',
    address: 'Huyện Kỳ Anh, Hà Tĩnh',
    province: 'Hà Tĩnh',
    urgency: 'high',
    peopleCount: 300,
    needs: { food: true, water: true, medicine: true, emergencyRescue: false },
    status: 'unassigned',
    lastUpdated: '8 phút trước',
    reportedAt: '2024-01-13 14:47',
    description:
      'Vùng trũng bị ngập sâu, hàng trăm hộ dân phải sơ tán khẩn cấp. Cần hỗ trợ toàn diện.',
    contactPerson: 'Ban chỉ huy PCTT huyện',
    contactPhone: '0988777666',
    dangerScore: 82,
    priorityScore: 87,
  },
  {
    id: 'RL-010',
    coordinates: { lat: 15.1194, lng: 108.803 },
    locationName: 'Huyện Tây Trà',
    address: 'Huyện Tây Trà, Quảng Ngãi',
    province: 'Quảng Ngãi',
    urgency: 'high',
    peopleCount: 140,
    needs: { food: true, water: true, medicine: true, emergencyRescue: true },
    status: 'unassigned',
    lastUpdated: '12 phút trước',
    reportedAt: '2024-01-13 14:43',
    description:
      'Lũ ống ập xuống trong đêm, cuốn trôi cầu và nhiều nhà dân. Có người mất tích, cần tìm kiếm khẩn cấp.',
    contactPerson: 'Chủ tịch UBND xã Trà Sơn',
    contactPhone: '0966555444',
    dangerScore: 90,
    priorityScore: 93,
  },
];

export const teamsData: Team[] = [
  {
    id: 'TEAM-001',
    name: 'Đội Cứu Hộ Lệ Thủy',
    currentLocation: { lat: 17.2185, lng: 106.7214 }, // Lệ Thủy, Quảng Bình approx
    vehicle: 'truck',
    capacity: { people: 30, cargo: 3000 },
    hasMedical: true,
    members: 15,
    leader: 'Nguyễn Văn A',
    contactPhone: '0912 345 678',
    status: 'moving',
    area: 'Lệ Thủy, Quảng Bình',
    currentAssignment: 'RL-005',
    memberDetails: [
      {
        id: 'M1',
        name: 'Nguyễn Văn A',
        role: 'Trưởng nhóm',
        avatar:
          'https://lh3.googleusercontent.com/aida-public/AB6AXuB48OJ4VxK1FjibJzIRFAfN4zjZrQFl7fIVFJDuVwVUvZ_pH009Ue9j8m-1Pf6_rpHWen-PY6494nRit7mjRuTCOEGiFm4nUnhpZEv3qw-dzjnD7TmaM3opv9Q4SPzNBQMPcq_AbFtHmXkU5CIWAys2wI1NJ-UW-nOqKSvH24YaL6b6yxGeyjcv61aPA5bUfSuz3R2Rl5dPuBjboHKpnMuvnY3z0Y-4Tx7JCKAzsrd-2htBAqhSFCQHZ42QkububzGoFQw67DdmhaM',
      },
      {
        id: 'M2',
        name: 'Lê Thị Mai',
        role: 'Y tá',
        avatar:
          'https://lh3.googleusercontent.com/aida-public/AB6AXuAaLovaKKBYkQP633wV0lH2InVDIeGFsmulwpK8a5fj91rb3dgjgyhhKGs9LrcedCDm7IfT8EMhIPfp1sKmP8t41nbx0t9Cw_03oE7EjzbZJjzkxOjXejdfmNC_JiYvJaxoHJKYmHcmFFshZSpxVigbPBrr1LTuTIeEh5RMKxQkjE1aVkp-Oo-Saq8oKALWvIaccTHJ8ycahmMPyTmmrBqlJbFbnuZJjkHkZ6EqAbL-Uqbpdg4pJbZTtD4st9myS6rZoQn5e5Q-XTY',
      },
      {
        id: 'M3',
        name: 'Trần Văn Hùng',
        role: 'Lái xe',
        avatar:
          'https://lh3.googleusercontent.com/aida-public/AB6AXuCxYWxRPn-hpDYN1Yms-VzVjSVLWHsrpAWQJCKdCP9wiQWexMZl6lne82CfPQ5C3BHyj6jbIiTgg-GIlG6Lu1NHdAoTIqUTxX0E1PKvAtKPVOWsG-jeySDpHnIhLjCTNuiA9oNS5Ktt6vDtwWOdqnVb6wvg79CnHQ67XflKhQfnt_HVoGnYNNonhBCLouzG6z4r1DVod0HtcD2-h59ngb2GP-35jokXNEzY0dbJ7SjKyLT0iIdhmK-RuV5Tj78wnEQzqEMRPC92wLE',
      },
      {
        id: 'M4',
        name: 'Phạm Minh Tuấn',
        role: 'Hậu cần',
        avatar:
          'https://lh3.googleusercontent.com/aida-public/AB6AXuAoYe5SeHqZ9wgzhaYcQU6om8uHBpRXDNkFlQpSvJDFZP-9PK71WYMAWybSSO8pAXXWCHF_Jx1t7LxEF2BiXYl7acBFsRtUPSw66vKoiDQnAslQGgNZniexC8BaqOTpTEaUh988PgrTQ4deQ0QxZ7KJaX7aR1znrWyWAV7lTrIob3xtYv2Vugub6fAEVMP9W05Ysr1XG67kxiQOB8K--UJCHcupGfyMGhHttkrTzKA0uOdG-r7SQtN9BC3v6KF7Mxth1HrHPKwKpSQ',
      },
    ],
  },
  {
    id: 'TEAM-002',
    name: 'Nhóm Y Tế Bạch Mai',
    currentLocation: { lat: 21.6961, lng: 104.8752 }, // Yên Bái
    vehicle: 'helicopter',
    capacity: { people: 15, cargo: 500 },
    hasMedical: true,
    members: 8,
    leader: 'Trần Thị Bích',
    contactPhone: '0901234567',
    status: 'rescuing',
    currentAssignment: 'RL-006',
    area: 'Yên Bái',
  },
  {
    id: 'TEAM-003',
    name: 'Đội Cano 03',
    currentLocation: { lat: 20.9599, lng: 107.0425 }, // Hạ Long
    vehicle: 'boat',
    capacity: { people: 25, cargo: 800 },
    hasMedical: false,
    members: 5,
    leader: 'Lê Văn Cường',
    contactPhone: '0977333444',
    status: 'moving',
    area: 'Hạ Long, Quảng Ninh',
  },
  {
    id: 'TEAM-004',
    name: 'Nhóm Hậu Cần Số 1',
    currentLocation: { lat: 22.4808, lng: 103.9737 }, // Lào Cai
    vehicle: 'truck',
    capacity: { people: 20, cargo: 5000 },
    hasMedical: false,
    members: 20,
    leader: 'Phạm Thị Dung',
    contactPhone: '0905111222',
    status: 'available',
    area: 'TP. Lào Cai',
  },
  {
    id: 'TEAM-005',
    name: 'Đội Tìm Kiếm Cứu Nạn',
    currentLocation: { lat: 22.1808, lng: 104.4737 }, // Bảo Yên
    vehicle: 'truck',
    capacity: { people: 20, cargo: 5000 },
    hasMedical: true,
    members: 12,
    leader: 'Hoàng Văn E',
    contactPhone: '0905111333',
    status: 'rescuing',
    area: 'Bảo Yên, Lào Cai',
  },
];

export const volunteerRequestsData: import('./types').VolunteerRequest[] = [
  {
    id: 'VOL-2024-8892',
    name: 'Nguyễn Văn A',
    phone: '0912 345 678',
    email: 'nguyenvana@gmail.com',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCZTiAqQReQxFLwBF9R_U0wifhUW1t-VtlzNyXZvDy7ygo5YkBp9kILH1axO6vRWjUeteYcE22y9wolEwuw0LxEDP6h7T9f48CsRxQD80pQ69muMMUMfL7QOGLAHIPuwt_uZyHVH3yfD6rPXPbNaZ9v5EhGZ_tz4yg-hZULIRoc4OlPiBBYmO2LU2EnU9v2W9E8W0gPP8VGD9X2cZKgTgWX_U-PS_m31OAZPX_3uWiafVDvopU42M3rpk2uc77yly63xOqI5PujyYQ',
    age: 28,
    gender: 'Nam',
    address: 'Hai Bà Trưng, Hà Nội',
    location: 'Hà Nội',
    status: 'new',
    skills: ['Sơ cấp cứu cơ bản', 'Bơi lội giỏi', 'Lái xe bán tải', 'Biết sử dụng bộ đàm'],
    experience:
      'Tôi đã có kinh nghiệm tham gia đội cứu hộ tự nguyện trong đợt lũ miền Trung năm 2020. Có khả năng bơi lội tốt, sức khỏe đảm bảo. Hiện tôi đang sở hữu một xe bán tải gầm cao (Ford Ranger) có thể hỗ trợ vận chuyển nhu yếu phẩm vào vùng ngập sâu trung bình. Đã tiêm đủ vaccine uốn ván và các mũi cơ bản.',
    submittedAt: '2024-09-15T08:30:00Z',
    images: [
      {
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDV21uiPEWtro-1EA8xqWim8fJ7zZywb4moKwp1pF-N21SL21NAzKCwR78U27ykzdPGiYHgYLouDdqBEug5OxQNNFgVmWk_JJ7mZ_YJac7UTNWSK-1RBwViLNLWRe4zJ8lQncqj4iBrR7lZ-7JMox8RAPQ-15Tf4fJ3zS4rHjmD5VSAvDa_VGxegn3HQPfA3nNrfHw9A1TJwGlfLXFKfcOfHkhayz75Fj95K7Gk7LQp9CBfNJKhNO0hlzhYle8aveZRffPxVVFIKkw',
        caption: 'Chứng chỉ sơ cấp cứu',
      },
      {
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCNIqeaVgIEJplTeiPTlR1JDiO2_dFOUIIXhUv4m37QMjEUItpPdwwbAsnsWH4WbOgtCPc8VaDtFvXNQKUYqWHbUiqal10tA52E_XR-12kTqmO1r2Cy_RhJDrSihb1wCHlRiwbCLfqYJylPiRx37jMnYqeIeEV3iM9JT_ZKT2ZucPj2YFWUgF7h9SnquIi2n_p-fFnAkBH3TEH3lhUphp5SwYh3amduQhmjp8X3A4msd6KO55teuso5b5dk8WQiv85F8-qEeOzAp10',
        caption: 'Xe bán tải cá nhân',
      },
    ],
    readiness: {
      health: true,
      vehicle: true,
      travel: true,
      commitment: false,
    },
  },
  {
    id: 'VOL-2024-8893',
    name: 'Trần Thị Bích',
    phone: '0987 654 321',
    email: 'tranthibich@example.com',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAaLovaKKBYkQP633wV0lH2InVDIeGFsmulwpK8a5fj91rb3dgjgyhhKGs9LrcedCDm7IfT8EMhIPfp1sKmP8t41nbx0t9Cw_03oE7EjzbZJjzkxOjXejdfmNC_JiYvJaxoHJKYmHcmFFshZSpxVigbPBrr1LTuTIeEh5RMKxQkjE1aVkp-Oo-Saq8oKALWvIaccTHJ8ycahmMPyTmmrBqlJbFbnuZJjkHkZ6EqAbL-Uqbpdg4pJbZTtD4st9myS6rZoQn5e5Q-XTY', // Placeholder or T letter avatar
    age: 26,
    gender: 'Nữ',
    address: 'Yên Bái',
    location: 'Yên Bái',
    status: 'new',
    skills: ['Cứu hộ đường thủy', 'Sơ cứu'],
    experience: 'Là vận động viên bơi lội, có kinh nghiệm cứu hộ sông nước.',
    submittedAt: '2024-09-15T08:00:00Z',
    images: [],
    readiness: {
      health: true,
      vehicle: false,
      travel: true,
      commitment: true,
    },
  },
  {
    id: 'VOL-2024-8894',
    name: 'Lê Văn Cường',
    phone: '0977 333 444',
    email: 'cuonglevan@example.com',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCEkDn5sReXVfL0p4SGbdBF3OvkiC1hXhpgOsIgqXCeU4NqJ1Zo4dtY2s6LbX9wx5fP144kmjpwi3MKQrmkjAky3i9co8pNO99AJ8fsq-Bda9lW9IOreyC2PAddrGlwM6zzZejRC9hskAh8AbwnY8AYw0uXJo30dbLE1Nv4BmpKLs9HPbwGk2fDyLuHGWKquHNyQjKgQrT5VKn5_myeK__RRVyNqzmljQXi7W8W1a99znUMCUpKYNeqqjfSlHWacKKo9IbiwQN5Duo',
    age: 30,
    gender: 'Nam',
    address: 'Hải Phòng',
    location: 'Hải Phòng',
    status: 'viewed',
    skills: ['Vận chuyển', 'Hậu cần'],
    experience: 'Có xe tải 2.5 tấn, sẵn sàng hỗ trợ vận chuyển hàng cứu trợ.',
    submittedAt: '2024-09-15T07:30:00Z',
    images: [],
    readiness: {
      health: true,
      vehicle: true,
      travel: true,
      commitment: true,
    },
  },
  {
    id: 'VOL-2024-8895',
    name: 'Hoàng Minh Tú',
    phone: '0905 111 333',
    email: 'minhtu@example.com',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBcoxQQgYgJTlb7xUMO9w5nbbBjuHxVXJaQPg42-tXZggZdVeALzx81ZD0mDgyjtuIJH7wo8iGO-K1_lExy0dqq16690W9LY_qjCSX2Wkc9MpkL9p6XPeKJNp1y6A_zZX9fFBme5qDwnDfHrGu4dvEhdiL9EqDXFpqA2G00Ni2FTv_Y6YFAMWmDll3F8xj-hi82g4drMEXGD_Qkqx7zKMBjhcwB2fh9yZc0V9wS3Uz2ZZVO83tBpc6kVG21wYoqd6CmPHnnNEZNxXI', // Placeholder
    age: 35,
    gender: 'Nam',
    address: 'Lào Cai',
    location: 'Lào Cai',
    status: 'viewed',
    skills: ['Sửa chữa điện', 'Sửa chữa nước'],
    experience: 'Kỹ sư điện nước, có thể hỗ trợ khắc phục sự cố sau bão.',
    submittedAt: '2024-09-15T06:30:00Z',
    images: [],
    readiness: {
      health: true,
      vehicle: false,
      travel: true,
      commitment: true,
    },
  },
];
