import type { ReliefLocation, Team, Headquarters } from './types';

export const HEADQUARTERS: Headquarters = {
  name: 'Nhà Văn hóa Sinh viên – Thủ Đức',
  coordinates: { lat: 10.87, lng: 106.805 }, // approx trung tâm Nhà Văn hóa Sinh viên, Thủ Đức
  address: 'Khu đô thị Đại học Quốc gia TP. HCM, Thành phố Thủ Đức, TP. Hồ Chí Minh, Việt Nam',
};

// Mock data từ các tỉnh miền Trung hay bị bão lũ
export const reliefLocationsData: ReliefLocation[] = [
  {
    id: 'RL-001',
    coordinates: { lat: 15.5694, lng: 108.0194 },
    locationName: 'Xã Trà Leng',
    address: 'Huyện Nam Trà My, Quảng Nam',
    province: 'Quảng Nam',
    urgency: 'high',
    peopleCount: 120,
    needs: { food: true, water: true, medicine: true, emergencyRescue: true },
    status: 'unassigned',
    lastUpdated: '5 phút trước',
    reportedAt: '2024-01-13 14:50',
    description:
      'KHẨN CẤP: Sạt lở đất nghiêm trọng, nhiều hộ dân bị vùi lấp, cần cứu hộ ngay lập tức. Đường sá bị chia cắt hoàn toàn.',
    contactPerson: 'Trưởng thôn Nguyễn Văn Sơn',
    contactPhone: '0905123456',
    dangerScore: 95,
    priorityScore: 98,
  },
  {
    id: 'RL-002',
    coordinates: { lat: 15.8801, lng: 108.338 },
    locationName: 'Thị trấn Hội An',
    address: 'Phố cổ Hội An, Quảng Nam',
    province: 'Quảng Nam',
    urgency: 'high',
    peopleCount: 250,
    needs: { food: true, water: true, medicine: false, emergencyRescue: false },
    status: 'unassigned',
    lastUpdated: '15 phút trước',
    reportedAt: '2024-01-13 14:40',
    description:
      'Ngập lụt nặng do mưa lớn kéo dài, nước dâng cao 1.5m. Nhiều gia đình bị cô lập, cần lương thực và nước sạch khẩn cấp.',
    contactPerson: 'Chủ tịch phường Minh An',
    contactPhone: '0912345678',
    dangerScore: 85,
    priorityScore: 90,
  },
  {
    id: 'RL-003',
    coordinates: { lat: 16.4637, lng: 107.5909 },
    locationName: 'Huyện Hướng Hóa',
    address: 'Huyện Hướng Hóa, Quảng Trị',
    province: 'Quảng Trị',
    urgency: 'high',
    peopleCount: 180,
    needs: { food: true, water: true, medicine: true, emergencyRescue: true },
    status: 'unassigned',
    lastUpdated: '10 phút trước',
    reportedAt: '2024-01-13 14:45',
    description:
      'Lũ quét ập đến bất ngờ, cuốn trôi nhiều nhà cửa. Có người bị thương và mất tích. Cần hỗ trợ y tế và tìm kiếm cứu nạn.',
    contactPerson: 'Ông Trần Văn Minh',
    contactPhone: '0987654321',
    dangerScore: 92,
    priorityScore: 95,
  },
  {
    id: 'RL-004',
    coordinates: { lat: 17.4739, lng: 106.6234 },
    locationName: 'Huyện Hương Khê',
    address: 'Huyện Hương Khê, Hà Tĩnh',
    province: 'Hà Tĩnh',
    urgency: 'medium',
    peopleCount: 95,
    needs: { food: true, water: false, medicine: true, emergencyRescue: false },
    status: 'unassigned',
    lastUpdated: '30 phút trước',
    reportedAt: '2024-01-13 14:25',
    description:
      'Ngập úng cục bộ, cần hỗ trợ lương thực và thuốc men cho người già, trẻ em. Tình hình đang được kiểm soát.',
    contactPerson: 'Bà Lê Thị Hoa',
    contactPhone: '0933444555',
    dangerScore: 65,
    priorityScore: 70,
  },
  {
    id: 'RL-005',
    coordinates: { lat: 16.8201, lng: 107.1004 },
    locationName: 'Thành phố Đông Hà',
    address: 'Đông Hà, Quảng Trị',
    province: 'Quảng Trị',
    urgency: 'medium',
    peopleCount: 150,
    needs: { food: true, water: true, medicine: false, emergencyRescue: false },
    status: 'on-the-way',
    lastUpdated: '20 phút trước',
    reportedAt: '2024-01-13 13:00',
    description: 'Ngập lụt do triều cường kết hợp mưa lớn. Đội cứu trợ đang trên đường đến.',
    contactPerson: 'UBND phường Đông Lễ',
    contactPhone: '0944555666',
    assignedTeamId: 'TEAM-001',
    dangerScore: 60,
    priorityScore: 65,
  },
  {
    id: 'RL-006',
    coordinates: { lat: 15.5753, lng: 107.7852 },
    locationName: 'Huyện Phước Sơn',
    address: 'Huyện Phước Sơn, Quảng Nam',
    province: 'Quảng Nam',
    urgency: 'high',
    peopleCount: 200,
    needs: { food: true, water: true, medicine: true, emergencyRescue: true },
    status: 'assigned',
    lastUpdated: '25 phút trước',
    reportedAt: '2024-01-13 13:30',
    description:
      'Sạt lở núi chặn đường, chia cắt hoàn toàn. Nhiều người bị thương, thiếu lương thực và nước uống.',
    contactPerson: 'Trưởng phòng QLTT',
    contactPhone: '0977888999',
    assignedTeamId: 'TEAM-002',
    dangerScore: 88,
    priorityScore: 92,
  },
  {
    id: 'RL-007',
    coordinates: { lat: 18.3464, lng: 105.9045 },
    locationName: 'Huyện Quỳnh Lưu',
    address: 'Huyện Quỳnh Lưu, Nghệ An',
    province: 'Nghệ An',
    urgency: 'low',
    peopleCount: 50,
    needs: { food: false, water: true, medicine: false, emergencyRescue: false },
    status: 'completed',
    lastUpdated: '2 giờ trước',
    reportedAt: '2024-01-13 11:00',
    description: 'Đã hoàn thành cung cấp nước sạch. Tình hình ổn định.',
    contactPerson: 'Trưởng xã Quỳnh Thắng',
    contactPhone: '0901234567',
    dangerScore: 30,
    priorityScore: 25,
  },
  {
    id: 'RL-008',
    coordinates: { lat: 16.0678, lng: 108.2208 },
    locationName: 'Quận Sơn Trà',
    address: 'Quận Sơn Trà, Đà Nẵng',
    province: 'Đà Nẵng',
    urgency: 'medium',
    peopleCount: 80,
    needs: { food: false, water: false, medicine: true, emergencyRescue: false },
    status: 'unassigned',
    lastUpdated: '40 phút trước',
    reportedAt: '2024-01-13 14:15',
    description: 'Cần hỗ trợ thuốc men cho bệnh nhân mãn tính do gián đoạn chuỗi cung ứng.',
    contactPerson: 'Trạm y tế phường Thọ Quang',
    contactPhone: '0905111222',
    dangerScore: 45,
    priorityScore: 55,
  },
  {
    id: 'RL-009',
    coordinates: { lat: 17.5883, lng: 106.3503 },
    locationName: 'Huyện Kỳ Anh',
    address: 'Huyện Kỳ Anh, Hà Tĩnh',
    province: 'Hà Tĩnh',
    urgency: 'high',
    peopleCount: 300,
    needs: { food: true, water: true, medicine: true, emergencyRescue: false },
    status: 'unassigned',
    lastUpdated: '8 phút trước',
    reportedAt: '2024-01-13 14:47',
    description:
      'Vùng trũng bị ngập sâu, hàng trăm hộ dân phải sơ tán khẩn cấp. Cần hỗ trợ toàn diện.',
    contactPerson: 'Ban chỉ huy PCTT huyện',
    contactPhone: '0988777666',
    dangerScore: 82,
    priorityScore: 87,
  },
  {
    id: 'RL-010',
    coordinates: { lat: 15.1194, lng: 108.803 },
    locationName: 'Huyện Tây Trà',
    address: 'Huyện Tây Trà, Quảng Ngãi',
    province: 'Quảng Ngãi',
    urgency: 'high',
    peopleCount: 140,
    needs: { food: true, water: true, medicine: true, emergencyRescue: true },
    status: 'unassigned',
    lastUpdated: '12 phút trước',
    reportedAt: '2024-01-13 14:43',
    description:
      'Lũ ống ập xuống trong đêm, cuốn trôi cầu và nhiều nhà dân. Có người mất tích, cần tìm kiếm khẩn cấp.',
    contactPerson: 'Chủ tịch UBND xã Trà Sơn',
    contactPhone: '0966555444',
    dangerScore: 90,
    priorityScore: 93,
  },
];

export const teamsData: Team[] = [
  {
    id: 'TEAM-001',
    name: 'Đội Cứu Hộ Xe Tải 01',
    currentLocation: { lat: 16.8201, lng: 107.1004 },
    vehicle: 'truck',
    capacity: { people: 30, cargo: 3000 },
    hasMedical: true,
    members: 8,
    leader: 'Thiếu tá Nguyễn Văn Bình',
    contactPhone: '0987654321',
    status: 'moving',
    currentAssignment: 'RL-005',
  },
  {
    id: 'TEAM-002',
    name: 'Đội Trực Thăng Cứu Hộ',
    currentLocation: { lat: 15.5753, lng: 107.7852 },
    vehicle: 'helicopter',
    capacity: { people: 15, cargo: 500 },
    hasMedical: true,
    members: 5,
    leader: 'Thượng úy Trần Văn Cường',
    contactPhone: '0901234567',
    status: 'rescuing',
    currentAssignment: 'RL-006',
  },
  {
    id: 'TEAM-003',
    name: 'Đội Y Tế Xe Máy 05',
    currentLocation: { lat: 16.0544, lng: 108.2022 },
    vehicle: 'motorcycle',
    capacity: { people: 2, cargo: 50 },
    hasMedical: true,
    members: 2,
    leader: 'Bác sĩ Phạm Thị Lan',
    contactPhone: '0912345678',
    status: 'available',
  },
  {
    id: 'TEAM-004',
    name: 'Đội Hậu Cần Xe Tải 02',
    currentLocation: { lat: 16.0544, lng: 108.2022 },
    vehicle: 'truck',
    capacity: { people: 20, cargo: 5000 },
    hasMedical: false,
    members: 6,
    leader: 'Đại úy Lê Minh Tuấn',
    contactPhone: '0905111222',
    status: 'available',
  },
  {
    id: 'TEAM-005',
    name: 'Đội Ca Nô Cứu Hộ 03',
    currentLocation: { lat: 16.0544, lng: 108.2022 },
    vehicle: 'boat',
    capacity: { people: 25, cargo: 800 },
    hasMedical: false,
    members: 4,
    leader: 'Trung úy Hoàng Văn Nam',
    contactPhone: '0977333444',
    status: 'available',
  },
  {
    id: 'TEAM-006',
    name: 'Đội Cứu Hộ Đặc Biệt',
    currentLocation: { lat: 16.0544, lng: 108.2022 },
    vehicle: 'truck',
    capacity: { people: 40, cargo: 4000 },
    hasMedical: true,
    members: 12,
    leader: 'Thiếu tá Vũ Đức Minh',
    contactPhone: '0933222111',
    status: 'available',
  },
];
