import { type RequestNotification } from '@/types/notifications';
import type { ExportItem } from './exportInventory';

export const requestNotifications: RequestNotification[] = [
  {
    id: 'req-01',
    requesterName: 'Nguyễn Văn A',
    requesterAvatar: '/avatars/avatar-default.png',
    requestType: 'CUU_TRO',
    description: 'Gia đình bị mắc kẹt do lũ, cần cứu trợ gấp',
    location: 'Hòa Vang, Đà Nẵng',
    createdAt: '2026-01-09 08:30',
    unread: true,
    evidences: [
      { type: 'IMAGE', url: '/evidence/flood-1.jpg' },
      {
        type: 'VIDEO',
        url: 'https://www.youtube.com/watch?v=_Td7JjCTfyc&feature=youtu.be',
        thumbnail: '/evidence/flood-thumb.jpg',
      },
    ],
  },
  {
    id: 'req-02',
    requesterName: 'Trần Thị B',
    requesterAvatar: '/avatars/user2.png',
    requestType: 'LUONG_THUC',
    description: 'Thiếu lương thực và nước uống cho 20 hộ dân',
    location: 'Phú Ninh, Quảng Nam',
    createdAt: '2026-01-09 07:50',
    unread: true,
    evidences: [{ type: 'IMAGE', url: '/evidence/food-1.jpg' }],
  },
  {
    id: 'req-03',
    requesterName: 'Lê Văn C',
    requesterAvatar: '/avatars/user3.png',
    requestType: 'CUU_TRO',
    description: 'Người già và trẻ em bị cô lập do sạt lở',
    location: 'Nam Trà My, Quảng Nam',
    createdAt: '2026-01-09 07:10',
    unread: true,
    evidences: [
      {
        type: 'VIDEO',
        url: '/evidence/landslide.mp4',
        thumbnail: '/evidence/landslide-thumb.jpg',
      },
    ],
  },
  {
    id: 'req-04',
    requesterName: 'Phạm Thị D',
    requesterAvatar: '/avatars/user4.png',
    requestType: 'KHAC',
    description: 'Cần hỗ trợ thuốc men cho người bị thương',
    location: 'Đại Lộc, Quảng Nam',
    createdAt: '2026-01-09 06:40',
    unread: false,
    evidences: [{ type: 'IMAGE', url: '/evidence/medical-1.jpg' }],
  },
  {
    id: 'req-05',
    requesterName: 'Hoàng Văn E',
    requesterAvatar: '/avatars/user5.png',
    requestType: 'LUONG_THUC',
    description: 'Thiếu gạo, mì tôm và sữa cho trẻ em',
    location: 'Krông Nô, Đắk Nông',
    createdAt: '2026-01-09 06:15',
    unread: false,
    evidences: [{ type: 'IMAGE', url: '/evidence/food-2.jpg' }],
  },
  {
    id: 'req-06',
    requesterName: 'Võ Thị F',
    requesterAvatar: '/avatars/user6.png',
    requestType: 'CUU_TRO',
    description: 'Nhà bị ngập sâu, không thể di chuyển',
    location: 'Hồng Lĩnh, Hà Tĩnh',
    createdAt: '2026-01-09 05:50',
    unread: true,
    evidences: [
      { type: 'IMAGE', url: '/evidence/flood-2.jpg' },
      { type: 'IMAGE', url: '/evidence/flood-3.jpg' },
    ],
  },
  {
    id: 'req-07',
    requesterName: 'Đặng Văn G',
    requesterAvatar: '/avatars/user7.png',
    requestType: 'KHAC',
    description: 'Cần hỗ trợ thuyền để sơ tán người dân',
    location: 'Lệ Thủy, Quảng Bình',
    createdAt: '2026-01-09 05:20',
    unread: true,
    evidences: [
      {
        type: 'VIDEO',
        url: '/evidence/boat.mp4',
        thumbnail: '/evidence/boat-thumb.jpg',
      },
    ],
  },
  {
    id: 'req-08',
    requesterName: 'Bùi Thị H',
    requesterAvatar: '/avatars/user8.png',
    requestType: 'LUONG_THUC',
    description: 'Thiếu thực phẩm khô cho khu tránh lũ',
    location: 'Tuy An, Phú Yên',
    createdAt: '2026-01-09 04:45',
    unread: false,
    evidences: [{ type: 'IMAGE', url: '/evidence/food-3.jpg' }],
  },
  {
    id: 'req-09',
    requesterName: 'Phan Văn K',
    requesterAvatar: '/avatars/user9.png',
    requestType: 'CUU_TRO',
    description: 'Có người bị thương nặng cần đưa đi cấp cứu',
    location: 'A Lưới, Thừa Thiên Huế',
    createdAt: '2026-01-09 04:10',
    unread: true,
    evidences: [
      {
        type: 'VIDEO',
        url: '/evidence/injury.mp4',
        thumbnail: '/evidence/injury-thumb.jpg',
      },
    ],
  },
  {
    id: 'req-10',
    requesterName: 'Ngô Thị L',
    requesterAvatar: '/avatars/user10.png',
    requestType: 'KHAC',
    description: 'Cần hỗ trợ chăn, áo ấm cho người già',
    location: 'Mù Cang Chải, Yên Bái',
    createdAt: '2026-01-09 03:30',
    unread: false,
    evidences: [{ type: 'IMAGE', url: '/evidence/clothes-1.jpg' }],
  },
];

export const mockTeams = [
  { id: 'team-1', name: 'Đội cứu trợ miền Trung' },
  { id: 'team-2', name: 'Đội cứu trợ miền Bắc' },
  { id: 'team-3', name: 'Đội y tế lưu động' },
];

export const mockItems: ExportItem[] = [
  {
    id: '1',
    name: 'Nước đóng chai',
    category: 'Nhu yếu phẩm',
    icon: 'water_drop',
    current: 450,
    capacity: 2000,
    unit: 'Thùng',
    quantity: 0,
    status: 'warning',
  },
  {
    id: '2',
    name: 'Gạo cứu trợ',
    category: 'Lương thực',
    icon: 'rice_bowl',
    current: 120,
    capacity: 500,
    unit: 'Bao',
    quantity: 0,
  },
  {
    id: '3',
    name: 'Thuốc y tế',
    category: 'Y tế',
    icon: 'medical_services',
    current: 250,
    capacity: 300,
    unit: 'Hộp',
    quantity: 0,
    status: 'danger',
  },
];
